// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QxHOracleLoader.Models;

namespace QxHOracleLoader.Migrations
{
    [DbContext(typeof(LoaderContext))]
    partial class LoaderContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("QxHOracleLoader.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ActualMinutesQty");

                    b.Property<int>("AvaiForSaleQty");

                    b.Property<int>("CompanyId");

                    b.Property<string>("ItemDescription");

                    b.Property<int>("NetworkId");

                    b.Property<int>("OrderQuantity");

                    b.Property<int>("OrderSldTdy");

                    b.Property<int>("PlanSeqId");

                    b.Property<int>("PlannedMinutesQty");

                    b.Property<string>("ShowCd");

                    b.Property<string>("ShowDate");

                    b.HasKey("ItemId");

                    b.ToTable("Item");
                });
#pragma warning restore 612, 618
        }
    }
}
